export { HomePage } from './Home';
export { ProjectsPage } from './Projects';
export { ProjectDetailPage } from './ProjectDetail';
export { DirectorsPage } from './Directors';
export { CareersPage } from './Careers';
export { ContactPage } from './Contact';
export { SustainabilityPage } from './Sustainability';
export { TendersPage } from './Tenders';
export { MediaPage } from './Media';
