# Generated by Django 6.0.1 on 2026-01-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('general', 'সাধারণ'), ('urgent', 'জরুরি'), ('tender', 'দরপত্র'), ('recruitment', 'নিয়োগ')], default='general', max_length=20)),
                ('published_date', models.DateField()),
                ('document', models.FileField(blank=True, upload_to='notices/')),
                ('link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-published_date', 'order'],
            },
        ),
    ]
