# Generated by Django 6.0.1 on 2026-01-16 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_featured', '-published_date', 'order'], 'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
        migrations.AddField(
            model_name='notice',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Display name for attachment', max_length=200),
        ),
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, help_text='Full notice content'),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for list view', max_length=300),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured section'),
        ),
        migrations.AddField(
            model_name='notice',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('urgent', 'Urgent'), ('tender', 'Tender'), ('recruitment', 'Recruitment')], default='general', max_length=20),
        ),
    ]
